#!/bin/bash

PORT=$(xmlstarlet sel -T -t -v /Config/Port /data/config/config.xml)

if [[ $(curl -sL "http://localhost:${PORT:-8989}/ping" | jq -r '.status' 2>/dev/null) = "OK" ]]; then
    exit 0
else
    exit 1
fi
