#!/usr/bin/env bash
# ==============================================================================
# Init folder & structures
# ==============================================================================
readonly CONFIG=/data/sabnzbd.ini

if [ ! -f "$CONFIG" ]; then
  echo "Bootstrapping SABnzbd folders and config..."
  mkdir -p /share/downloads /share/incomplete-downloads
  cat <<CONFIG > "$CONFIG"
[misc]
download_dir = /share/incomplete-downloads
complete_dir = /share/downloads
check_new_rel = 0
CONFIG
fi

