name: Build (minecraft)

on:
  push:
    branches: master
    paths:
      - minecraft/Dockerfile
      - minecraft/rootfs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: config
        name: Extract config version
        run: |
          awk ' /image:/ { print "image=" $2 }' minecraft/config.yaml | tr -d '"' >> "$GITHUB_OUTPUT"
          awk ' /version:/ { print "version=" $2 }' minecraft/config.yaml | tr -d '"' >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: publish
        name: Push container
        uses: docker/build-push-action@v6
        with:
          context: minecraft
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.config.outputs.image }}:${{ steps.config.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
