name: Build pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - '*/Dockerfile'
      - '*/test.ya?ml'
      - '*/rootfs/**'

jobs:
  inspect:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.changed }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: addons
        name: Determine changed addons
        env:
          START_REF: HEAD
          END_REF: "HEAD~${{ (github.event.pull_request && github.event.pull_request.commits) || 1}}"
        run: |
          git diff --name-only -r "$START_REF" "$END_REF" | awk -F '/' '{ print $1 }' | sort -u | xargs -I % -n 1 jq -r .slug %/config.json 2>/dev/null | jq -rnR '"changed=\([inputs]|@json)"' >> "$GITHUB_OUTPUT"

  build:
    needs: inspect
    if: needs.inspect.outputs.addons != '[]'
    strategy:
      matrix:
        addon: ${{ fromJSON(needs.inspect.outputs.addons) }}
    uses: ./.github/workflows/build.yml
    with:
      addon: ${{ matrix.addon }}
      publish: ${{ github.event.pull_request && github.event.pull_request.merged }}
      ref: ${{ github.sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
